new stuff for kenny from Newstuffforkenny
Sage-Bionetworks/synapsegraphdb pull request #5
Opened 2016-09-16 22:12 UTC by kendama

2016-09-27 19:03 UTC, kdaily requested changes
Consolidate all fxns duplicated across scripts. Remove printing to stdout (print to stderr using `sys.stderr.write`)

2016-09-27 19:03 UTC, kdaily commented on activities2Graph.py
> +        return entityDict
Move try inside `for ent in query` loop - return both `entityDict` and a list of bad entities caught by the exception?

2016-09-27 19:03 UTC, kdaily commented on activities2Graph.py
> +                for version in range(1,int(versionNumber)):
No guarantee that all versions between 1 and the current version exist. Use [REST call](http://hud.rel.rest.doc.sagebase.org.s3-website-us-east-1.amazonaws.com/GET/entity/id/version.html) to get all versions of a file.

2016-09-27 19:03 UTC, kdaily commented on activities2Graph.py
> +	    #Remove containers by ignoring layers, projects, and previews
move comment up, abstract the list `[1,2,3]` to a global var so it's defined and can be modified if necessary.

2016-09-27 19:03 UTC, kdaily commented on activities2Graph.py
> +    global newId
use local var, pass into function.

2016-09-27 19:03 UTC, kdaily commented on activities2Graph.py
> +    global newId
pass in `newId` generator

2016-09-27 19:03 UTC, kdaily commented on activities2Graph.py
> +                try:
move try/catch inside of `addNodesandEdges` - around specific place(s) where there are errors. consider logging errors to a static file as well as the console (stderr)

2016-09-27 19:03 UTC, kdaily commented on convertSynapse2Graph.py
> +    global newId
pass in instead of global

2016-09-27 19:03 UTC, kdaily commented on convertSynapse2Graph.py
> +    try:
move try inside of for loop

2016-09-27 19:03 UTC, kdaily commented on convertSynapse2Graph.py
>  def getEntities(projectId):
merge with `getEntities` that is in `activities2Graph.py` (or move to a shared library file and call the same one)

2016-09-27 19:03 UTC, kdaily commented on convertSynapse2Graph.py
> +    parser.add_argument('--p', type=int, default=6, help='Specify the pool size for the multiprocessing module')
default to 2 or 4?

2016-09-27 19:03 UTC, kdaily commented on convertSynapse2Graph.py
> +        if proj in ['syn582072', 'syn3218329', 'syn2044761', 'syn2351328', 'syn1450028']:
define this at the top (or allow parameter for it)

2016-09-27 19:03 UTC, kdaily commented on convertSynapse2Graph.py
> +    with open('graphSynapse.json', 'w') as fp:
allow user to specify name of output file (or just use stdout)

2016-09-27 19:03 UTC, kdaily commented on examples/cypher_queries.txt
> +## Useful Cypher queries for Neo4j Database
rename as `cypher_queries.md` so Github renders as Markdown.

2016-09-27 19:03 UTC, kdaily commented on load2Neo4jDB.py
> +    dQuery = dQuery % edges.name
give more descriptive names for the queries

2016-09-27 19:03 UTC, kdaily commented on load2Neo4jDB.py
> +    graph.run(dQuery)
turn into a loop over all queries to run with `graph.run`.

2016-09-27 19:03 UTC, kdaily commented on load2Neo4j_deprecated.py
> +authenticate("ec2-54-91-28-8.compute-1.amazonaws.com:7474", "neo4j", "sage2016")
remove this and restart machine

2016-09-27 19:03 UTC, kdaily commented on load2Neo4j_deprecated.py
> +import gc
remove whole file - use diff version of `load2Neo4j.py`.

2016-09-27 22:31 UTC, kendama commented on activities2Graph.py
> +	    #Remove containers by ignoring layers, projects, and previews
doneish

2016-09-27 22:31 UTC, kendama commented on activities2Graph.py
> +    global newId
done

2016-09-27 22:37 UTC, kendama commented on activities2Graph.py
> +    global newId
done

2016-09-27 22:37 UTC, kendama commented on convertSynapse2Graph.py
>  def getEntities(projectId):
done

2016-09-27 22:37 UTC, kendama commented on convertSynapse2Graph.py
> +    global newId
done

2016-09-27 22:38 UTC, kendama commented on convertSynapse2Graph.py
> +    parser.add_argument('--p', type=int, default=6, help='Specify the pool size for the multiprocessing module')
used 4

2016-09-27 22:38 UTC, kendama commented on convertSynapse2Graph.py
> +        if proj in ['syn582072', 'syn3218329', 'syn2044761', 'syn2351328', 'syn1450028']:
done

2016-09-27 22:39 UTC, kendama commented on examples/cypher_queries.txt
> +## Useful Cypher queries for Neo4j Database
done

2016-09-28 00:08 UTC, kendama commented on activities2Graph.py
> +        return entityDict
done

2016-09-28 00:09 UTC, kendama commented on activities2Graph.py
> +                try:
done

2016-09-28 00:38 UTC, kendama commented on convertSynapse2Graph.py
> +    with open('graphSynapse.json', 'w') as fp:
finito

2016-09-28 00:56 UTC, kendama commented on load2Neo4jDB.py
> +    dQuery = dQuery % edges.name
done

2016-09-28 00:56 UTC, kendama commented on load2Neo4jDB.py
> +    graph.run(dQuery)
done

2016-09-28 16:48 UTC, kdaily commented
I see responses to most changes (hooray!) but don't see any changes to the code from what we reviewed? ¿Que paso?

2016-09-28 22:55 UTC, kdaily requested changes

2016-09-28 22:55 UTC, kdaily commented on convertSynapse2Graph.py
> +            continue
add logging statement here with error and synapse ID of entity

2016-09-28 22:55 UTC, kdaily commented on convertSynapse2Graph.py
> +            sys.stderr.write('Skipping current relationship retrieval due to targetId KeyError')
add id of activity in output

2016-09-28 22:55 UTC, kdaily commented on convertSynapse2Graph.py
> +                    ent = syn.restGET('/entity/%s/version/%s' %(ent['synId'],version))
`ent = syn.get(, version=?)`

2016-09-28 22:56 UTC, kdaily approved these changes

2016-09-28 22:56 UTC, merged